### ISSUE TITLE
Is gutenberg.run down or discontinued?

### ISSUE THREAD

**Issue by huubl** [WordPress/gutenberg.run#30]
It seems that gutenberg.run is not reachable:

https://downforeveryoneorjustme.com/gutenberg.run?proto=https

**Comment by pkevan** [comment]
you can access the same functionality that was available here: https://playground.wordpress.net/gutenberg.html

**Comment by courtneyr-dev** [comment]
https://gutenberg.run now redirects to https://playground.wordpress.net/gutenberg.html.
